name: 'Deb Crerie '
favicon: null
layout_spectrum: 0.03733555879443884
typography_spectrum: 0.25490402802824974
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.7628700919449329
  lightness: 0.8695820085704327
  saturation: 0.8264089999720454
  rhythmicContrast: 0.06349175982177258
purpose: []
